### ISSUE TITLE
Source code / readme does not contain any licensing info

### ISSUE THREAD

**Issue by joshka** [MarkNijhof/Fohjin#1]
Hi Mark,
I really enjoyed your CQRS series of posts. Thanks for sharing.
The source code on github does not contain any information on licensing the code.

Cheers,
Josh

**Comment by MarkNijhof** [comment]
Hi Josh,

Thanks for your comment, the license is the same as on my blog :-) will fix that in the source sometime.

-Mark

**Comment by joshka** [comment]
Cool, thanks Mark. For the sake of closing this issue, that license is "This work is licensed under a Creative Commons Attribution 3.0 Unported License." http://creativecommons.org/licenses/by/3.0/
